## Institute of Applied AI Engineers

#### 1. Generate a 1D NumPy array containing numbers from -2 to 2 in increments of 0.2. Use optional start and step arguments of np.arange() function.

In [8]:
import numpy as np
a = np.arange(-2,2,0.2)
print(a)

[ -2.00000000e+00  -1.80000000e+00  -1.60000000e+00  -1.40000000e+00
  -1.20000000e+00  -1.00000000e+00  -8.00000000e-01  -6.00000000e-01
  -4.00000000e-01  -2.00000000e-01  -4.44089210e-16   2.00000000e-01
   4.00000000e-01   6.00000000e-01   8.00000000e-01   1.00000000e+00
   1.20000000e+00   1.40000000e+00   1.60000000e+00   1.80000000e+00]


#### 2. Generate another 1D NumPy array containing 11 equally spaced values between 0.5 and 1.5. Extract every second element of the array

In [9]:
print(np.linspace(0.5,1.5,11))

[ 0.5  0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3  1.4  1.5]


#### 3. Create a 4x4 array with arbitrary values.Extract every element from the second row.


In [10]:
ev=np.random.uniform(1, 100, size=16).reshape(4,4)
print(ev,"\n\n\n",ev[1:2,0:])

[[ 20.71400855  69.23401622  11.12443952  31.86325524]
 [ 78.03425141  91.91859935  23.3409836   62.24961874]
 [ 23.11647962  74.19651911  26.46189992  71.24963893]
 [ 68.74931932  17.78201835  28.89494638  46.7967991 ]] 


 [[ 78.03425141  91.91859935  23.3409836   62.24961874]]


#### 4. Extract every element from the third column

In [6]:
print(ev,"\n\n\n",ev[0:,2])

[[ 29.58201272  71.7122244   79.8542459   75.18435007]
 [ 67.30926802  82.10370322  34.11480665  12.0239744 ]
 [ 30.70279616  81.44053263  53.1778313   90.07957881]
 [  3.8163573    5.86779572  23.38350292  51.99640414]] 


 [ 79.8542459   34.11480665  53.1778313   23.38350292]


#### 5. Assign a value of 0.21 to upper left 2x2 subarray.

In [4]:
ev[0:2,0:2] = 0.2 
print(ev)

[[  0.2          0.2         94.78488647  80.52783306]
 [  0.2          0.2         83.26326002  89.89713591]
 [ 69.8242346   63.2484797   85.94027875  56.79837131]
 [ 96.62173865  64.23537827  25.10920544  50.99663399]]


#### 6. Read an 2D array from the file exercise1_4.dat. You can usethe function np.loadtxt():
data = np.loadtxt(‘exercise1_4.dat’)

#### Split the array into four subblocks (upper left, upper right, lower left, lower right) using np.split(). Construct then the full array again with np.concatenate(). You can visualize the various arrays with matplotlib’s imshow(), i.e. import pylab pylab.imshow(data)

In [7]:
data = np.loadtxt('exercise1_4.dat')
print(data)

ValueError: could not convert string to float: b'Student'